name: ewriq

on:
  schedule:
    - cron: "0 0 * * *" # her gün UTC 00:00'da çalışır
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
